
<Structures>
  <Structure Name="ComboInfo" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" RLECompression="1" AutoCreateStructsize="4096">
    <Elements>
      <Element Offset="0" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000000" Description="totalHits" DisplayMethod="Unsigned Integer"/>
      <Element Offset="4" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000004" Description="maxLengthThisReset" DisplayMethod="Unsigned Integer"/>
      <Element Offset="8" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000008" DisplayMethod="Unsigned Integer"/>
      <Element Offset="12" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000000C" Description="maxLength" DisplayMethod="Unsigned Integer"/>
      <Element Offset="16" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000010" Description="maxDmg" DisplayMethod="Unsigned Integer"/>
      <Element Offset="20" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000014" Description="maxCombo" DisplayMethod="Unsigned Integer"/>
      <Element Offset="24" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000018" DisplayMethod="Unsigned Integer"/>
      <Element Offset="26" Vartype="2 Bytes" Bytesize="2" OffsetHex="0000001A" DisplayMethod="Hexadecimal"/>
      <Element Offset="28" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="0000001C" DisplayMethod="Unsigned Integer"/>
      <Element Offset="44" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000002C" Description="lengthToo" DisplayMethod="Unsigned Integer"/>
      <Element Offset="48" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000030" Description="length" DisplayMethod="Unsigned Integer"/>
      <Element Offset="52" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000034" Description="dmg" DisplayMethod="Unsigned Integer"/>
      <Element Offset="56" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000038" Description="rawDmg" DisplayMethod="Unsigned Integer"/>
      <Element Offset="60" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000003C" Description="redDmg" DisplayMethod="Unsigned Integer"/>
      <Element Offset="64" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000040" DisplayMethod="Unsigned Integer"/>
      <Element Offset="68" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000044" Description="length2Too" DisplayMethod="Unsigned Integer"/>
      <Element Offset="72" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000048" Description="length2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="76" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000004C" Description="dmg2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="80" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000050" Description="rawDmg2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="84" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000054" Description="redDmg2" DisplayMethod="Unsigned Integer"/>
      <Element Offset="88" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000058" DisplayMethod="Unsigned Integer"/>
      <Element Offset="96" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000060" Description="firstComboLength" DisplayMethod="Unsigned Integer"/>
      <Element Offset="100" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000064" Description="firstComboDmg" DisplayMethod="Unsigned Integer"/>
      <Element Offset="104" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000068" DisplayMethod="Hexadecimal"/>
      <Element Offset="108" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000006C" Description="correctionValue" DisplayMethod="Unsigned Integer"/>
      <Element Offset="112" Vartype="Pointer" Bytesize="4" OffsetHex="00000070" DisplayMethod="Unsigned Integer"/>
      <Element Offset="116" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000074" DisplayMethod="Unsigned Integer"/>
      <Element Offset="156" Vartype="Pointer" Bytesize="4" OffsetHex="0000009C" DisplayMethod="Unsigned Integer"/>
      <Element Offset="160" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="000000A0" DisplayMethod="Unsigned Integer"/>
      <Element Offset="200" Vartype="Pointer" Bytesize="4" OffsetHex="000000C8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="204" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="000000CC" DisplayMethod="Unsigned Integer"/>
      <Element Offset="244" Vartype="Pointer" Bytesize="4" OffsetHex="000000F4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="248" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="000000F8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="288" Vartype="Pointer" Bytesize="4" OffsetHex="00000120" DisplayMethod="Unsigned Integer"/>
      <Element Offset="292" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000124" DisplayMethod="Unsigned Integer"/>
      <Element Offset="332" Vartype="Pointer" Bytesize="4" OffsetHex="0000014C" DisplayMethod="Unsigned Integer"/>
      <Element Offset="336" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000150" DisplayMethod="Unsigned Integer"/>
      <Element Offset="376" Vartype="Pointer" Bytesize="4" OffsetHex="00000178" DisplayMethod="Unsigned Integer"/>
      <Element Offset="380" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="0000017C" DisplayMethod="Unsigned Integer"/>
      <Element Offset="420" Vartype="Pointer" Bytesize="4" OffsetHex="000001A4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="424" Vartype="4 Bytes" Bytesize="4" RLECount="22" OffsetHex="000001A8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="512" Vartype="Double" Bytesize="8" OffsetHex="00000200" DisplayMethod="Unsigned Integer"/>
      <Element Offset="520" Vartype="4 Bytes" Bytesize="4" RLECount="29" OffsetHex="00000208" DisplayMethod="Unsigned Integer"/>
      <Element Offset="636" Vartype="Pointer" Bytesize="4" OffsetHex="0000027C" DisplayMethod="Unsigned Integer"/>
      <Element Offset="640" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000280" DisplayMethod="Unsigned Integer"/>
      <Element Offset="680" Vartype="Pointer" Bytesize="4" OffsetHex="000002A8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="684" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="000002AC" DisplayMethod="Unsigned Integer"/>
      <Element Offset="724" Vartype="Pointer" Bytesize="4" OffsetHex="000002D4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="728" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="000002D8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="768" Vartype="Pointer" Bytesize="4" OffsetHex="00000300" DisplayMethod="Unsigned Integer"/>
      <Element Offset="772" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000304" DisplayMethod="Unsigned Integer"/>
      <Element Offset="812" Vartype="Pointer" Bytesize="4" OffsetHex="0000032C" DisplayMethod="Unsigned Integer"/>
      <Element Offset="816" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000330" DisplayMethod="Unsigned Integer"/>
      <Element Offset="856" Vartype="Pointer" Bytesize="4" OffsetHex="00000358" DisplayMethod="Unsigned Integer"/>
      <Element Offset="860" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="0000035C" DisplayMethod="Unsigned Integer"/>
      <Element Offset="900" Vartype="Pointer" Bytesize="4" OffsetHex="00000384" DisplayMethod="Unsigned Integer"/>
      <Element Offset="904" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000388" DisplayMethod="Unsigned Integer"/>
      <Element Offset="944" Vartype="Pointer" Bytesize="4" OffsetHex="000003B0" DisplayMethod="Unsigned Integer"/>
      <Element Offset="948" Vartype="4 Bytes" Bytesize="4" RLECount="275" OffsetHex="000003B4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="2048" Vartype="Double" Bytesize="8" OffsetHex="00000800" DisplayMethod="Unsigned Integer"/>
      <Element Offset="2056" Vartype="4 Bytes" Bytesize="4" RLECount="510" OffsetHex="00000808" DisplayMethod="Unsigned Integer"/>
    </Elements>
  </Structure>
</Structures>