
<Structures>
  <Structure Name="ComboInfo" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" RLECompression="1" AutoCreateStructsize="4096">
    <Elements>
      <Element Offset="0" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000000" DisplayMethod="Unsigned Integer"/>
      <Element Offset="12" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000000C" Description="maxLength" DisplayMethod="Unsigned Integer"/>
      <Element Offset="16" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000010" Description="maxDmg" DisplayMethod="Unsigned Integer"/>
      <Element Offset="20" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000014" Description="maxCombo" DisplayMethod="Unsigned Integer"/>
      <Element Offset="24" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000018" DisplayMethod="Unsigned Integer"/>
      <Element Offset="26" Vartype="2 Bytes" Bytesize="2" OffsetHex="0000001A" DisplayMethod="Hexadecimal"/>
      <Element Offset="28" Vartype="4 Bytes" Bytesize="4" RLECount="21" OffsetHex="0000001C" DisplayMethod="Unsigned Integer"/>
      <Element Offset="112" Vartype="Pointer" Bytesize="4" OffsetHex="00000070" DisplayMethod="Unsigned Integer"/>
      <Element Offset="116" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000074" DisplayMethod="Unsigned Integer"/>
      <Element Offset="156" Vartype="Pointer" Bytesize="4" OffsetHex="0000009C" DisplayMethod="Unsigned Integer"/>
      <Element Offset="160" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="000000A0" DisplayMethod="Unsigned Integer"/>
      <Element Offset="200" Vartype="Pointer" Bytesize="4" OffsetHex="000000C8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="204" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="000000CC" DisplayMethod="Unsigned Integer"/>
      <Element Offset="244" Vartype="Pointer" Bytesize="4" OffsetHex="000000F4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="248" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="000000F8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="288" Vartype="Pointer" Bytesize="4" OffsetHex="00000120" DisplayMethod="Unsigned Integer"/>
      <Element Offset="292" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000124" DisplayMethod="Unsigned Integer"/>
      <Element Offset="332" Vartype="Pointer" Bytesize="4" OffsetHex="0000014C" DisplayMethod="Unsigned Integer"/>
      <Element Offset="336" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000150" DisplayMethod="Unsigned Integer"/>
      <Element Offset="376" Vartype="Pointer" Bytesize="4" OffsetHex="00000178" DisplayMethod="Unsigned Integer"/>
      <Element Offset="380" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="0000017C" DisplayMethod="Unsigned Integer"/>
      <Element Offset="420" Vartype="Pointer" Bytesize="4" OffsetHex="000001A4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="424" Vartype="4 Bytes" Bytesize="4" RLECount="22" OffsetHex="000001A8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="512" Vartype="Double" Bytesize="8" OffsetHex="00000200" DisplayMethod="Unsigned Integer"/>
      <Element Offset="520" Vartype="4 Bytes" Bytesize="4" RLECount="29" OffsetHex="00000208" DisplayMethod="Unsigned Integer"/>
      <Element Offset="636" Vartype="Pointer" Bytesize="4" OffsetHex="0000027C" DisplayMethod="Unsigned Integer"/>
      <Element Offset="640" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000280" DisplayMethod="Unsigned Integer"/>
      <Element Offset="680" Vartype="Pointer" Bytesize="4" OffsetHex="000002A8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="684" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="000002AC" DisplayMethod="Unsigned Integer"/>
      <Element Offset="724" Vartype="Pointer" Bytesize="4" OffsetHex="000002D4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="728" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="000002D8" DisplayMethod="Unsigned Integer"/>
      <Element Offset="768" Vartype="Pointer" Bytesize="4" OffsetHex="00000300" DisplayMethod="Unsigned Integer"/>
      <Element Offset="772" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000304" DisplayMethod="Unsigned Integer"/>
      <Element Offset="812" Vartype="Pointer" Bytesize="4" OffsetHex="0000032C" DisplayMethod="Unsigned Integer"/>
      <Element Offset="816" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000330" DisplayMethod="Unsigned Integer"/>
      <Element Offset="856" Vartype="Pointer" Bytesize="4" OffsetHex="00000358" DisplayMethod="Unsigned Integer"/>
      <Element Offset="860" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="0000035C" DisplayMethod="Unsigned Integer"/>
      <Element Offset="900" Vartype="Pointer" Bytesize="4" OffsetHex="00000384" DisplayMethod="Unsigned Integer"/>
      <Element Offset="904" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000388" DisplayMethod="Unsigned Integer"/>
      <Element Offset="944" Vartype="Pointer" Bytesize="4" OffsetHex="000003B0" DisplayMethod="Unsigned Integer"/>
      <Element Offset="948" Vartype="4 Bytes" Bytesize="4" RLECount="275" OffsetHex="000003B4" DisplayMethod="Unsigned Integer"/>
      <Element Offset="2048" Vartype="Double" Bytesize="8" OffsetHex="00000800" DisplayMethod="Unsigned Integer"/>
      <Element Offset="2056" Vartype="4 Bytes" Bytesize="4" RLECount="510" OffsetHex="00000808" DisplayMethod="Unsigned Integer"/>
    </Elements>
  </Structure>
</Structures>