//
// Created by PC_volt on 15/05/2021.
//

#ifndef MELTYLIB_STAGE_H
#define MELTYLIB_STAGE_H

enum StageName : unsigned int {
    RANDOM_SELECT,
    ARTIFICIAL_EDEN,
    CLASSIC_HOME_EVENING_PARTY,
    CLASSIC_HOME_INVADE,
    SHADE_TOWN_MAD_PARADE,
    TOHNOS_MANSION_MAIN_GATE,
    NIGHT_OF_WALPURGIS,
    SABBATH,
    MIDNIGHT_PARK,
    MAGICAL_KOHAKU_PRISON,
    BACK_ALLEY = 10,

    SCHOOL_RUSH = 12,
    IRON_MAIDEN,

    HOLOGRAM_SUMMER = 16,
    STARLIGHT_CROSSING,
    WITCH_ON_THE_HOLY_NIGHT,
    THROUGH_THE_LOOKING_GLASS,
    CLASSIC,
    TEMPLE_THE_SEVENTH_HEAVEN,
    DOCTOR_KOHAKU_GARAGE,
    GREAT_CATS_VILLAGE,
    TOHNOS_MANSION_CENTRAL_GARDEN,
    HUGE_LIBRARY,
    FOREST_OF_KING_CRUEL,
    BATTLE_FIELD,
    NARVOUS_STRAY_VANGUARD,
    RED_MOON_SCHERZO,
    LOST_WORLDS_BIOGRAPHY,
    NECO_NO_YOU_MAY,
    LOSER_CATS_COMPANY = 32,

    PHANTOM_OF_THE_OPERA = 34,
    CARRY_BACK_OLD_VILLAGE,
    TEMPLE_THE_SEVENTH_HEAVEN_2,
    STRANGER,
    IN_THE_PARK,
    ON_THE_PARK,
    SPIRAL_UROBOROS,
    CHERRY_BLOSSOM,
    DESERT_TOWN,
    COATING_EARTH_BLACK_LAND_TEXTURE,
    EMERALD_TABLE_MELTY_BLOOD_TEXTURE,
    SLEEPING_FOREST,
    FAREWELL_TOWN,
    FATEFUL_SHOWDOWN,
    THE_CROSSING_CROSSING,
    MAGICAL_KOHAKU_PRISON_2,
    NO_CONTROL_RED,
    NECO_BURST_CAMP,
    STRANGER_2,
    ARIMAS_CHINESE_KEMPO_HOME,
    SAYONARA_DEAR_FRIEND,
    AND_NOTHING_HEART,
    ONE_LIFE_ONE_DEATE,
    G_TABLE,
    G_TABLE_2,
    GOOD_MORNING_ANIMA_MUNDI = 59
};

#endif //MELTYLIB_STAGE_H
